### ISSUE TITLE
Not supported for the HTML5 platform

### ISSUE THREAD

**Issue by Hujunjob** [3ddelano/discord_gd_examples#1]
WARNING: Disabling HTTPClient's host verification is not supported for the HTML5 platform, host will be verified.
Access to fetch at 'https://discord.com/api/v9/channels/90030***782/messages' from origin 'http://localhost:8060' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by 3ddelano** [comment]
I would really recommend not trying this in the browser since your bot token will be accessible which is quite dangerous and not recommended and I haven't tried it. Currently I am hosting the Godot bot on a linux server using Google Cloud Platform's free 24x7 tier. But anyways I will still try to look into this error.
